services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            POSTGRES_HOST: db:5432
        ports:
            - "8000:8000"
        depends_on:
            - db
        develop:
            watch:
                - action: rebuild
                  path: ./app
                  target: /code/app
                - action: rebuild
                  path: requirements.txt
                  

    db:
        image: postgres:17-alpine
        environment:
            POSTGRES_DB: gym-manager
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: alpha07
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - "5438:5432"

volumes:
    database:
