"""add new field payment method to memberschema

Revision ID: 1359a541b063
Revises: 1dea3d8f74d2
Create Date: 2026-02-08 01:58:19.845554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1359a541b063'
down_revision: Union[str, Sequence[str], None] = '1dea3d8f74d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberschema', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberschema', 'payment_method')
    # ### end Alembic commands ###
