"""initial migrations

Revision ID: 1dea3d8f74d2
Revises: 
Create Date: 2026-02-07 18:33:29.067242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dea3d8f74d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberaddressschema',
                    sa.Column(
                        'street_line_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'street_line_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('userschema',
                    sa.Column(
                        'username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_userschema_username'),
                    'userschema', ['username'], unique=False)
    op.create_table('memberschema',
                    sa.Column(
                        'first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('phone_number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('membership_start_date',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('membership_end_date',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('date_of_birth',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER',
                                                'NOT_SPECIFIED', name='gender'), nullable=True),
                    sa.Column('membership_type', sa.Enum(
                        'GYM', 'SWIMMING', name='membershiptype'), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('address_id', sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['memberaddressschema.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_memberschema_email'),
                    'memberschema', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberschema_email'), table_name='memberschema')
    op.drop_table('memberschema')
    op.drop_index(op.f('ix_userschema_username'), table_name='userschema')
    op.drop_table('userschema')
    op.drop_table('memberaddressschema')
    # ### end Alembic commands ###
